#!/bin/bash

function cd() {
  ## "$@" refers to the shell scripts command line arguments. passing "builtin" ensures that the function doesnt call itself but the builtin cd. It would normally call itself since shell scripts take precedence over builtins
  builtin cd "$@"

  ## Default path to virtualenv in your projects. EDIT this according to the name you give to your virtual envionments,
  DEFAULT_ENV_PATH="./.venv"

  ## If virtual env folder is found then activate the vitualenv
  function activate_venv() {
    if [[ -f "${DEFAULT_ENV_PATH}/bin/activate" ]] ; then 
      source "${DEFAULT_ENV_PATH}/bin/activate"
      echo "Activating ${VIRTUAL_ENV}"
    fi
  }

  if [[ -z "$VIRTUAL_ENV" ]] ; then
    activate_venv
  else
    ## check the current folder belong to earlier VIRTUAL_ENV folder
    # if yes then do nothing
    # else deactivate then run a new env folder check
      parentdir="$(dirname ${VIRTUAL_ENV})"
    # if the current path is not a subdirectory of the earlier VIRTUAL_ENV folder
      if [[ "$PWD"/ != "$parentdir"/* ]] ; then
        echo "Deactivating ${VIRTUAL_ENV}"
        deactivate
        activate_venv
      fi
  fi
}
