#!/bin/bash

main(){
# ask the user to exter the file path
read -p "Enter the location of the file(from $HOME) that you want to increase the spacing of: ~/" filepath

# checks if an input was provided 
if [[ -z $filepath ]]; then
	echo "No input entered."
	return
else
	# check if the file path exists
	if [[ -f $HOME/$filepath ]]; then
		# read the file and print it to stdout with spacing between each line 
		# -r prevents a backslash escapes from being interpreted 
		# IFS= prevent leading/trailing whitespace from being trimmed
		echo "File being read and printed as output."
		while IFS= read -r line
		do
  			echo  "$line"
			echo
			echo
		done < "$HOME/$filepath"
	else
		echo "File $filepath does not exist."
	fi
fi
}

main
